### ISSUE TITLE
Composer install error

### ISSUE THREAD

**Issue by ellioseven** [phase2/pattern-lab-drupal-theme#3]
I get an error on the initial composer install:

```
cd pattern-lab
composer install
```

Gets:

```
  Problem 1
    - Installation request for pattern-lab/unified-asset-installer v0.5.5 -> satisfiable by pattern-lab/unified-asset-installer[v0.5.5].
    - pattern-lab/unified-asset-installer v0.5.5 requires composer-plugin-api 1.0.0 -> no matching package found.
  Problem 2
    - pattern-lab/unified-asset-installer v0.5.5 requires composer-plugin-api 1.0.0 -> no matching package found.
    - pattern-lab/core v0.7.2 requires pattern-lab/unified-asset-installer ~0.5 -> satisfiable by pattern-lab/unified-asset-installer[v0.5.5].
    - Installation request for pattern-lab/core v0.7.2 -> satisfiable by pattern-lab/core[v0.7.2].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by cferthorney** [comment]
According to https://github.com/phase2/drupal-lab/commit/d981d99bad17741c95922a747580db070c3ff2af the version of  `aleksip/plugin-data-transform` needs locking down to `0.10.1`.  This worked for me.  I'll sort a PR as soon as possible.

**Comment by malcomio** [comment]
After making the changes in #5, I got the following error on running `composer install`:

```
PHP Fatal error:  Uncaught Error: Class 'Colors\Color' not found in /Users/malcolm/Documents/Code/d8/web/themes/contrib/patternlab/pattern-lab/vendor/pattern-lab/core/src/PatternLab/Console.php:43
Stack trace:
#0 /Users/malcolm/Documents/Code/d8/web/themes/contrib/patternlab/pattern-lab/vendor/pattern-lab/core/src/PatternLab/InstallerUtil.php(56): PatternLab\Console::init()
#1 /Users/malcolm/Documents/Code/d8/web/themes/contrib/patternlab/pattern-lab/vendor/pattern-lab/core/src/PatternLab/InstallerUtil.php(399): PatternLab\InstallerUtil::init()
#2 /Users/malcolm/Documents/Code/d8/web/themes/contrib/patternlab/pattern-lab/core/src/PatternLab/Installer.php(45): PatternLab\InstallerUtil::postPackageInstall(Object(Composer\Installer\PackageEvent))
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(282): PatternLab\Installer::postPackageInstall(Object(Composer\Installer\PackageEvent))
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatche in /Users/malcolm/Documents/Code/d8/web/themes/contrib/patternlab/pattern-lab/vendor/pattern-lab/core/src/PatternLab/Console.php on line 43

Fatal error: Uncaught Error: Class 'Colors\Color' not found in /Users/malcolm/Documents/Code/d8/web/themes/contrib/patternlab/pattern-lab/vendor/pattern-lab/core/src/PatternLab/Console.php:43
Stack trace:
#0 /Users/malcolm/Documents/Code/d8/web/themes/contrib/patternlab/pattern-lab/vendor/pattern-lab/core/src/PatternLab/InstallerUtil.php(56): PatternLab\Console::init()
#1 /Users/malcolm/Documents/Code/d8/web/themes/contrib/patternlab/pattern-lab/vendor/pattern-lab/core/src/PatternLab/InstallerUtil.php(399): PatternLab\InstallerUtil::init()
#2 /Users/malcolm/Documents/Code/d8/web/themes/contrib/patternlab/pattern-lab/core/src/PatternLab/Installer.php(45): PatternLab\InstallerUtil::postPackageInstall(Object(Composer\Installer\PackageEvent))
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(282): PatternLab\Installer::postPackageInstall(Object(Composer\Installer\PackageEvent))
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatche in /Users/malcolm/Documents/Code/d8/web/themes/contrib/patternlab/pattern-lab/vendor/pattern-lab/core/src/PatternLab/Console.php on line 43
```
